INSERT INTO Favourite (user_email, channel_name) VALUES
('breannakey@example.com', 'BeitolAbbas TV Channel'),
('breannakey@example.com', 'Outdoor Channel International'),
('breannakey@example.com', 'Eliktisadia El Oula TV'),
('breannakey@example.com', 'Nexus TV'),
('breannakey@example.com', 'Discovery Turbo India'),
('breannakey@example.com', 'CNN Brasil'),
('breannakey@example.com', 'Canal E'),
('breannakey@example.com', 'TVRI Jawa Timur'),
('breannakey@example.com', 'Fast & FunBox HD'),
('breannakey@example.com', 'MNC TV'),
('nking@example.org', 'Universal TV México'),
('nking@example.org', 'Rede Gênesis'),
('nking@example.org', 'Somali National TV'),
('nking@example.org', 'RTBF La Trois'),
('nking@example.org', 'Atyraý'),
('nking@example.org', 'TNL TV'),
('nking@example.org', 'Kanal 7'),
('waltonlucas@example.net', 'France 24 Français'),
('waltonlucas@example.net', 'Ruang Trampil'),
('waltonlucas@example.net', 'NRT 4'),
('waltonlucas@example.net', 'Sports Connect'),
('waltonlucas@example.net', 'FTV Taiwan'),
('waltonlucas@example.net', 'Eurosport 1 Polska'),
('waltonlucas@example.net', 'Tiankov Folk'),
('joshua90@example.net', 'Vivid TV Europe'),
('joshua90@example.net', 'Bet 9JA League 2'),
('joshua90@example.net', 'Espreso TV'),
('qlowery@example.org', 'Zanis TV'),
('qlowery@example.org', 'Sky Mix Ireland'),
('qlowery@example.org', 'Digi Shala 39'),
('tammylee@example.org', 'PPTV HD 36'),
('tammylee@example.org', 'E-Vidya 180'),
('tammylee@example.org', 'Pitaara'),
('tammylee@example.org', 'LPB'),
('tammylee@example.org', 'Cruise 1st TV'),
('tammylee@example.org', 'NLC News'),
('tammylee@example.org', 'TV 1 Oberösterreich'),
('tammylee@example.org', 'Congress Channel 1'),
('tammylee@example.org', 'Insan TV'),
('tammylee@example.org', 'Rede CNT Rio de Janeiro'),
('kingkristen@example.net', 'Dish Network 101'),
('kingkristen@example.net', 'Prameya News 7'),
('shawn35@example.com', 'KTV Al Qurain'),
('shawn35@example.com', 'KTV 2'),
('shawn35@example.com', 'Rai Italia Nord America'),
('shawn35@example.com', 'Telecupole'),
('shawn35@example.com', 'E-Vidya 37'),
('jonathan33@example.com', 'Band Paraná'),
('jonathan33@example.com', 'Oras ng Himala'),
('jonathan33@example.com', 'TNT Brasil'),
('duransabrina@example.net', 'Alsahraa TV'),
('duransabrina@example.net', 'Telekanal 360°'),
('duransabrina@example.net', 'Bhakti Sagar'),
('duransabrina@example.net', 'Poehali! International'),
('laura29@example.net', 'Kibris TV'),
('laura29@example.net', 'Studio Universal América Latina'),
('laura29@example.net', 'DTX Polska'),
('laura29@example.net', 'Planet M Shopping'),
('laura29@example.net', 'Telesecundaria'),
('laura29@example.net', 'Hasken Rana'),
('laura29@example.net', 'Telemolise'),
('laura29@example.net', 'Canal 10'),
('susan54@example.com', 'Fiji One'),
('susan54@example.com', 'Berita RTM'),
('susan54@example.com', 'Al Shasha Alwan'),
('susan54@example.com', 'Lux.TV'),
('susan54@example.com', 'Karbalaeia TV'),
('lburton@example.net', 'Super TV Aristanis'),
('lburton@example.net', 'FilmBox Arthouse Africa & Turkey & Middle East'),
('lburton@example.net', '4 Kurd'),
('kellerchelsea@example.org', 'ESPN 4 Nederland'),
('kellerchelsea@example.org', 'Aflak TV'),
('kellerchelsea@example.org', 'Star World HD India'),
('kellerchelsea@example.org', 'Investigation Discovery India'),
('kellerchelsea@example.org', 'Réunion 1ère'),
('kellerchelsea@example.org', 'Canal 4'),
('kellerchelsea@example.org', 'NTA Yoruba'),
('kellerchelsea@example.org', 'Warner TV Romania'),
('kellerchelsea@example.org', 'Uzay Haber'),
('michellebrown@example.com', 'IEN Doros 3'),
('michellebrown@example.com', 'Praiseland TV'),
('michellebrown@example.com', 'SA TV'),
('michellebrown@example.com', 'Ilm va Tabiat'),
('michellebrown@example.com', 'Canal + Action Nederland'),
('michellebrown@example.com', 'Anointing TV Channel'),
('michellebrown@example.com', 'Canal do Cliente'),
('ujones@example.net', 'A Más +'),
('ujones@example.net', 'Sony Pal'),
('ujones@example.net', 'CDTV'),
('ujones@example.net', 'NK TV Bangla'),
('ujones@example.net', 'Radio Javan TV'),
('ujones@example.net', 'HBO Family Asia'),
('ujones@example.net', 'ESAN TV'),
('ujones@example.net', 'Qazaqstan'),
('michaelvelasquez@example.com', 'TVN Movies Pinoy'),
('cheryladams@example.org', 'KAUU-TV'),
('oshepard@example.com', 'Redlight HD'),
('oshepard@example.com', 'Rossiya 24'),
('oshepard@example.com', 'Más Chic Lationamérica'),
('oshepard@example.com', 'Brighter TV'),
('michaelpeters@example.org', 'Schelkovo TV'),
('michaelpeters@example.org', 'GEM Travel'),
('michaelpeters@example.org', 'Family Hikayat'),
('michaelpeters@example.org', 'VANDE Gujarat 3');
